# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            D.Q
tagline:          ''
description:      'The world is all that is the case.'
url:              http://dqis.me

author:
  name:           'dq'
  url:            https://github.com/dqisme

paginate:         50

# Custom vars
version:          1.0.0

# Gems
plugins: [jekyll-paginate]